### ISSUE TITLE
flash problems cont

### ISSUE THREAD

**Issue by astramage** [embeddedkink/lockbox-firmware#5]
i am unable to find "upload file system image" i tried some more with the web flasher and i just get this

![image](https://github.com/embeddedkink/lockbox-firmware/assets/133549141/7554f556-8cd9-4f67-98ca-20102de28c0c)

**Comment by embeddedkink** [comment]
This means that the flasher gets stuck before it can even start with the actual flashing. If you followed all the instructions, there might be an issue with the board. You can try verifying that the boot button actually works. It is available as a normal IO pin after the device has booted.

The upload filesystem button is located here in the UI:
![image](https://github.com/embeddedkink/lockbox-firmware/assets/83869659/afbeb0bd-bea1-417a-b039-449cff644647)

**Comment by astramage** [comment]
the whole platform sub-folder isn't there
![image](https://github.com/embeddedkink/lockbox-firmware/assets/133549141/90155635-44a0-4076-a623-ece7850c8eab)

"You can try verifying that the boot button actually works." I'm not sure what you mean

**Comment by embeddedkink** [comment]
Can you try opening a PIO terminal and running `pio run --target uploadfs`? I'm hoping that might turn up a useful error message.
Was the board previously set up to work with OTA?

Because the flashing process fails at that stage, I'm guessing that the board doesn't go into boot mode. That may be because the board is faulty. If you upload a simple sketch that does something like `digitalWrite(LED_BUILTIN, digitalRead(D3))` you can check if the button works. (I find it rather unlikely that that will turn out to be the problem but it's the only thing i can think of right now)

I haven't looked into the web flasher in a while but I don't think that it puts the board into boot mode using the UART like PIO does. I'm not exactly sure why that is. That's at least why the flashing takes an extra step with the webflasher compared to PIO.

It shouldn't make a difference at this stage I think but the links you sent in the previous issue said that the chip you use is a 12E. Can you confirm using PIO that that is the case?

**Comment by astramage** [comment]
tried pio terminal got this 
![image](https://github.com/embeddedkink/lockbox-firmware/assets/133549141/a1102e97-f17d-4e1f-92c6-7bcc272f05b7)

"Was the board previously set up to work with OTA?" the board was never set up for anything its straight out of the box, I am new to MCUs and honestly don't really know what I'm doing, sorry.

**Comment by embeddedkink** [comment]
Oh no I've made a very dumb mistake. I should have a fix really soon. PIO runs a script to automatically generate the right version number which doesn't work on Windows.

**Comment by embeddedkink** [comment]
with merge #6 you should be able to get more info out of `pio run --target uploadfs`, let me know

**Comment by astramage** [comment]
i didn't need to use the terminal it work perfectly, thank you
